"use client"
import Header from "@/components/header";
import { productsStore } from "@/store/product_store";
import { StoreProvider } from "@/store/StoreContext";
import "./globals.css";
import Footer from "@/components/footer";
import YandexMetrika from "@/components/yaMetrika";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({ children }) {

  if (typeof window !== "undefined") {
    const products = JSON.parse(localStorage.getItem("cart"))
    const cookie = JSON.parse(localStorage.getItem("cookie"))
    
    if(localStorage.getItem("cart")){
      productsStore.init();
      productsStore.setCart(products)
      productsStore.setCookie(cookie) 
      
    }else{
      productsStore.init();
    }

    if(localStorage.getItem("cookie")){
      productsStore.setCookie(cookie) 
    }else{
      productsStore.setCookie(true) 
    }
  }
  

  return (
    <html lang="ru" data-scroll-behavior="smooth">
      <head>
        <title>Промавтоматика-т</title>
        <meta name="description" content="Производство и продажа LVDT - датчиков линейного перемещения, LPS датчиков, BDT блоков. Оказание услуг в наладке и отладке оборудования промышленной автоматики." />
        <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <meta name="apple-mobile-web-app-title" content="MyWebSite" />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body>
        <StoreProvider>
          <Header></Header>
          {children}
          <Footer></Footer>
        </StoreProvider>
        <div id="cart" className="Close"></div>
        <div id="error" className="Close"></div>
        <YandexMetrika/>
        
        
      </body>
    </html>
  );
}
