import Header from "@/components/header";
import { productsStore } from "@/store/product_store";
import { StoreProvider } from "@/store/StoreContext";
import "./globals.css";
import Footer from "@/components/footer";
import YandexMetrika from "@/components/yaMetrika";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



export default function RootLayout({ children }) {
  
  

  return (
    <html lang="ru" data-scroll-behavior="smooth">
      <head>
        <title>Промавтоматика-т</title>
        <meta name="description" content="Производство и продажа LVDT - датчиков линейного перемещения, LPS датчиков, BDT блоков. Оказание услуг в наладке и отладке оборудования промышленной автоматики." />
        <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <meta name="apple-mobile-web-app-title" content="MyWebSite" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="preload" href="/assets/images/Customers/Incontrol.svg" as="image" type="image/svg" />
        <link rel="preload" href="/assets/images/Customers/Jam.png" as="image" type="image/png" />
        <link rel="preload" href="/assets/images/Customers/Sibir.svg" as="image" type="image/svg" />
        <link rel="preload" href="/assets/images/Customers/TSA.svg" as="image" type="image/svg" />
        <link rel="preload" href="/assets/images/Customers/Turbosystem.svg" as="image" type="image/svg" />
        <link rel="preload" href="/assets/images/Customers/Unipro.svg" as="image" type="image/svg" />
        <link rel="preload" href="/assets/images/Customers/InterRao.svg" as="image" type="image/svg" />
        <link rel="preload" href="/assets/images/Customers/BashCom.svg" as="image" type="image/svg" />
        <link rel="preload" href="/assets/images/Customers/реостат.png" as="image" type="image/png" />
        <link rel="preload" href="/assets/images/Customers/ИНМАТЕК.png" as="image" type="image/png" />
        <link rel="preload" href="/assets/images/Customers/Промстрой.png" as="image" type="image/png" />
        <link rel="preload" href="/assets/images/Customers/техновар кс.svg" as="image" type="image/svg" />
        <link rel="preload" href="/assets/images/Customers/ЭМСК.png" as="image" type="image/png" />
        <link rel="preload" href="/assets/images/Customers/Промавтоматика.svg" as="image" type="image/svg" />
        <link rel="preload" href="/assets/images/Customers/ker_auto.svg" as="image" type="image/svg" />
        <link rel="preload" href="/assets/images/Customers/sil_mash.svg" as="image" type="image/svg" />
        <link rel="preload" href="/assets/images/BDT/BDT.jpg" as="image" type="image/jpg" />
        <link rel="preload" href="/assets/images/BFS/BFS_sl_1.jpg" as="image" type="image/jpg" />
        <link rel="preload" href="/assets/images/FS/FS.png" as="image" type="image/png" />
        <link rel="preload" href="/assets/images/LPS/LPS.png" as="image" type="image/png" />
      </head>
      <body>
        <StoreProvider>
          <Header></Header>
          {children}
          <Footer></Footer>
        </StoreProvider>
        <div id="cart" className="Close"></div>
        <div id="error" className="Close"></div>
        <YandexMetrika/>
        
        
      </body>
    </html>
  );
}
