"use client";
import Header from "@/components/header";
import ProductStore, { productsStore } from "@/store/product_store";
import { StoreProvider } from "@/store/StoreContext";
import { createContext, useEffect } from "react";
import "./globals.css";
import Footer from "@/components/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const Context = createContext(null)



export default function RootLayout({ children }) {
    useEffect(() => {
      const products = JSON.parse(localStorage.getItem("cart"))
      console.log(products);
      
      if(localStorage.getItem("cart")){
        productsStore.init();
        productsStore.setCart(products)
      }else{
        productsStore.init();
      }
      
    }, []);

  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <Header></Header>
          {children}
          <Footer></Footer>
        </StoreProvider>
        <div id="cart" className="Close"></div>
      </body>
    </html>
  );
}
